name: record

on:
  workflow_dispatch:        # 手动触发

permissions:
  contents: read
  actions: write
  id-token: write

concurrency:
  group: record
  cancel-in-progress: false

jobs:
  record:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 最长录制 6 小时

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: huggingface/tailscale-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inotify-tools curl jq netcat-openbsd
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Node.js dependencies
        run: |
          npm install
          
      - name: Install ffmpeg with full codec support
        run: |
          # 安装完整版本的 ffmpeg，确保支持 RTSP
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:savoury1/ffmpeg4
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Verify ffmpeg RTSP support
        run: |
          echo "Checking ffmpeg version and protocols:"
          ffmpeg -version
          echo "Supported protocols:"
          ffmpeg -protocols 2>/dev/null | grep rtsp || echo "RTSP not found in protocols"

      - name: Setup TeraBox credentials
        run: |
          echo "TeraBox configuration loaded from secrets"
          echo "Legacy API credentials:"
          echo "  TERABOX_JSTOKEN is set: ${{ secrets.TERABOX_JSTOKEN != '' }}"
          echo "  TERABOX_BDSTOKEN is set: ${{ secrets.TERABOX_BDSTOKEN != '' }} (optional)"
          echo "  TERABOX_COOKIE is set: ${{ secrets.TERABOX_COOKIE != '' }}"
          echo "Node.js library credentials:"
          echo "  TERABOX_NDUS is set: ${{ secrets.TERABOX_NDUS != '' }}"
          echo "  TERABOX_APPID is set: ${{ secrets.TERABOX_APPID != '' }}"
          echo "  TERABOX_UPLOADID is set: ${{ secrets.TERABOX_UPLOADID != '' }}"
          echo "  TERABOX_BROWSERID is set: ${{ secrets.TERABOX_BROWSERID != '' }}"

      - name: Run recorder
        env:
          RTSP_URL: ${{ secrets.RTSP_URL }}
          # Legacy API credentials (fallback)
          TERABOX_JSTOKEN: ${{ secrets.TERABOX_JSTOKEN }}
          TERABOX_BDSTOKEN: ${{ secrets.TERABOX_BDSTOKEN }}
          TERABOX_COOKIE: ${{ secrets.TERABOX_COOKIE }}
          # Node.js library credentials (preferred)
          TERABOX_NDUS: ${{ secrets.TERABOX_NDUS }}
          TERABOX_APPID: ${{ secrets.TERABOX_APPID }}
          TERABOX_UPLOADID: ${{ secrets.TERABOX_UPLOADID }}
          TERABOX_BROWSERID: ${{ secrets.TERABOX_BROWSERID }}
          TERABOX_REMOTE_FOLDER: ${{ vars.TERABOX_REMOTE_FOLDER || '/rtsp-videos' }}
        run: |
          chmod +x ./record.sh ./terabox_upload.sh ./terabox_upload_wrapper.sh ./upload_terabox.js
          ./record.sh

